"""initial schema

Revision ID: b93084332416
Revises: 
Create Date: 2026-09-01 04:45:25.887910+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = 'b93084332416'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('status_emoji', sa.String(length=64), nullable=True),
    sa.Column('status_text', sa.String(length=200), nullable=True),
    sa.Column('status_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('presence', sa.String(length=16), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('is_service_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_handle'), ['handle'], unique=True)

    op.create_table('sessions',
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_name', sa.String(length=160), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_refresh_token_hash', ['refresh_token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_sessions_user_id_revoked_at', ['user_id', 'revoked_at'], unique=False)

    op.create_table('workspaces',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=26), nullable=True),
    sa.Column('allowed_email_domains', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_workspaces_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_slug'), ['slug'], unique=True)

    op.create_table('apps',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('accent_color', sa.String(length=16), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('owner_workspace_id', sa.String(length=26), nullable=True),
    sa.Column('author_id', sa.String(length=26), nullable=True),
    sa.Column('panel_url', sa.Text(), nullable=True),
    sa.Column('sidebar_url', sa.Text(), nullable=True),
    sa.Column('event_webhook_url', sa.Text(), nullable=True),
    sa.Column('default_width', sa.Integer(), nullable=False),
    sa.Column('requested_scopes', sa.JSON(), nullable=False),
    sa.Column('slash_commands', sa.JSON(), nullable=False),
    sa.Column('event_subscriptions', sa.JSON(), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('is_first_party', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_apps_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_workspace_id'], ['workspaces.id'], name=op.f('fk_apps_owner_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_apps')),
    sa.UniqueConstraint('slug', name='uq_apps_slug')
    )
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.create_index('ix_apps_owner_workspace_id', ['owner_workspace_id'], unique=False)

    op.create_table('channels',
    sa.Column('workspace_id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('topic', sa.String(length=400), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('dm_key', sa.String(length=600), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=26), nullable=True),
    sa.Column('last_message_id', sa.String(length=26), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_channels_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_channels_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels')),
    sa.UniqueConstraint('workspace_id', 'slug', name='uq_channels_workspace_id_slug')
    )
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.create_index('ix_channels_dm_key', ['dm_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_channels_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_channels_workspace_id_kind', ['workspace_id', 'kind'], unique=False)

    op.create_table('workspace_invites',
    sa.Column('workspace_id', sa.String(length=26), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by', sa.String(length=26), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_workspace_invites_invited_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_invites_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_invites')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_workspace_invites_token_hash'))
    )
    with op.batch_alter_table('workspace_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_invites_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_invites_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_members'))
    )
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_members_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('uq_workspace_members_workspace_id_user_id', ['workspace_id', 'user_id'], unique=True)

    op.create_table('app_installations',
    sa.Column('workspace_id', sa.String(length=26), nullable=False),
    sa.Column('app_id', sa.String(length=26), nullable=False),
    sa.Column('installed_by', sa.String(length=26), nullable=True),
    sa.Column('granted_scopes', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('bot_user_id', sa.String(length=26), nullable=True),
    sa.Column('channel_ids', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('installed_version', sa.String(length=32), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], name=op.f('fk_app_installations_app_id_apps'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bot_user_id'], ['users.id'], name=op.f('fk_app_installations_bot_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['installed_by'], ['users.id'], name=op.f('fk_app_installations_installed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_app_installations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_installations')),
    sa.UniqueConstraint('workspace_id', 'app_id', name='uq_app_installations_workspace_id_app_id')
    )
    with op.batch_alter_table('app_installations', schema=None) as batch_op:
        batch_op.create_index('ix_app_installations_workspace_id_enabled', ['workspace_id', 'is_enabled'], unique=False)

    op.create_table('channel_members',
    sa.Column('channel_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('last_read_message_id', sa.String(length=26), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('notification_level', sa.String(length=16), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('section', sa.String(length=80), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('hidden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_members_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_channel_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_members')),
    sa.UniqueConstraint('channel_id', 'user_id', name='uq_channel_members_channel_id_user_id')
    )
    with op.batch_alter_table('channel_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_members_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_channel_members_user_id_channel_id', ['user_id', 'channel_id'], unique=False)

    op.create_table('files',
    sa.Column('workspace_id', sa.String(length=26), nullable=False),
    sa.Column('uploader_id', sa.String(length=26), nullable=True),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('mime_type', sa.String(length=160), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('storage_backend', sa.String(length=16), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('thumbnail_key', sa.Text(), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('app_id', sa.String(length=26), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], name=op.f('fk_files_app_id_apps'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('fk_files_uploader_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_files_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index('ix_files_uploader_id_id', ['uploader_id', 'id'], unique=False)
        batch_op.create_index('ix_files_workspace_id_id', ['workspace_id', 'id'], unique=False)

    op.create_table('messages',
    sa.Column('channel_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=True),
    sa.Column('app_id', sa.String(length=26), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('client_msg_id', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=True),
    sa.Column('mentioned_user_ids', sa.JSON(), nullable=False),
    sa.Column('mentions_everyone', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.String(length=26), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('reply_user_ids', sa.JSON(), nullable=False),
    sa.Column('last_reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('also_sent_to_channel', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edit_count', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], name=op.f('fk_messages_app_id_apps'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_messages_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.id'], name=op.f('fk_messages_parent_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_messages_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('channel_id', 'client_msg_id', name='uq_messages_channel_id_client_msg_id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_channel_id_id', ['channel_id', 'id'], unique=False)
        batch_op.create_index('ix_messages_parent_id_id', ['parent_id', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_user_id'), ['user_id'], unique=False)

    op.create_table('app_storage_items',
    sa.Column('installation_id', sa.String(length=26), nullable=False),
    sa.Column('scope_key', sa.String(length=80), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['app_installations.id'], name=op.f('fk_app_storage_items_installation_id_app_installations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_storage_items')),
    sa.UniqueConstraint('installation_id', 'scope_key', 'key', name='uq_app_storage_items_install_scope_key')
    )
    with op.batch_alter_table('app_storage_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_storage_items_installation_id'), ['installation_id'], unique=False)

    op.create_table('app_tokens',
    sa.Column('installation_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['app_installations.id'], name=op.f('fk_app_tokens_installation_id_app_installations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_tokens'))
    )
    with op.batch_alter_table('app_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_tokens_installation_id'), ['installation_id'], unique=False)
        batch_op.create_index('ix_app_tokens_token_hash', ['token_hash'], unique=True)

    op.create_table('message_attachments',
    sa.Column('message_id', sa.String(length=26), nullable=False),
    sa.Column('file_id', sa.String(length=26), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_message_attachments_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_attachments_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_attachments')),
    sa.UniqueConstraint('message_id', 'file_id', name='uq_message_attachments_message_id_file_id')
    )
    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_attachments_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_attachments_message_id'), ['message_id'], unique=False)

    op.create_table('reactions',
    sa.Column('message_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('emoji', sa.String(length=80), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_reactions_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reactions')),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='uq_reactions_message_id_user_id_emoji')
    )
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.create_index('ix_reactions_message_id_emoji', ['message_id', 'emoji'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_index('ix_reactions_message_id_emoji')

    op.drop_table('reactions')
    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_attachments_message_id'))
        batch_op.drop_index(batch_op.f('ix_message_attachments_file_id'))

    op.drop_table('message_attachments')
    with op.batch_alter_table('app_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_app_tokens_token_hash')
        batch_op.drop_index(batch_op.f('ix_app_tokens_installation_id'))

    op.drop_table('app_tokens')
    with op.batch_alter_table('app_storage_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_storage_items_installation_id'))

    op.drop_table('app_storage_items')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_user_id'))
        batch_op.drop_index('ix_messages_parent_id_id')
        batch_op.drop_index('ix_messages_channel_id_id')

    op.drop_table('messages')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index('ix_files_workspace_id_id')
        batch_op.drop_index('ix_files_uploader_id_id')
        batch_op.drop_index(batch_op.f('ix_files_checksum_sha256'))

    op.drop_table('files')
    with op.batch_alter_table('channel_members', schema=None) as batch_op:
        batch_op.drop_index('ix_channel_members_user_id_channel_id')
        batch_op.drop_index(batch_op.f('ix_channel_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_channel_members_channel_id'))

    op.drop_table('channel_members')
    with op.batch_alter_table('app_installations', schema=None) as batch_op:
        batch_op.drop_index('ix_app_installations_workspace_id_enabled')

    op.drop_table('app_installations')
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.drop_index('uq_workspace_members_workspace_id_user_id')
        batch_op.drop_index(batch_op.f('ix_workspace_members_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_members_user_id'))

    op.drop_table('workspace_members')
    with op.batch_alter_table('workspace_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_invites_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_invites_email'))

    op.drop_table('workspace_invites')
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_index('ix_channels_workspace_id_kind')
        batch_op.drop_index(batch_op.f('ix_channels_workspace_id'))
        batch_op.drop_index('ix_channels_dm_key')

    op.drop_table('channels')
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_index('ix_apps_owner_workspace_id')

    op.drop_table('apps')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_slug'))

    op.drop_table('workspaces')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_id_revoked_at')
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index('ix_sessions_refresh_token_hash')

    op.drop_table('sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_handle'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
